# Generated by Django 3.2.9 on 2023-04-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('sexe', models.CharField(max_length=200)),
                ('wilaya', models.CharField(max_length=200)),
                ('commune', models.CharField(max_length=200)),
                ('a_fait_un_test', models.CharField(max_length=200)),
                ('frequence_a_boire_alcool', models.CharField(max_length=200)),
                ('frequence_a_utiliser_drogue', models.CharField(max_length=200)),
                ('a_des_rapports_sexuels_non_proteges', models.CharField(max_length=200)),
                ('a_ete_vaccine', models.CharField(max_length=200)),
                ('a_remarquer_jaunisse', models.CharField(max_length=200)),
                ('avez_vous_etes_diagnostiquer', models.CharField(max_length=200)),
                ('avez_vous_voyager', models.CharField(max_length=200)),
                ('avez_vous_ressenti_fatigue', models.CharField(max_length=200)),
            ],
        ),
    ]
